elecv2p:
  image: byxiaopeng/elecv2pjd
  container_name: elecv2p
  restart: always
  privileged: true
  ports:
    - "8100:80"
    - "8101:8001"
    - "8102:8002"
  volumes:
    - "/elecv2p/JSFile:/elecV2P/script/JSFile"
    - "/elecv2p/Lists:/elecV2P/script/Lists"
    - "/elecv2p/Store:/elecV2P/script/Store"
    - "/elecv2p/Shell:/elecV2P/script/Shell"
    - "/elecv2p/rootCA:/elecV2P/rootCA"
    - "/elecv2p/efss:/elecV2P/efss"
  environment:
     #https://app.pm2.io/
    - PM2_PUBLIC_KEY=
    - PM2_SECRET_KEY=
