name: elecv2p
on:
  push:
    branches:
      - master
  watch:
    types: started
  schedule:
    - cron: 35 21 * * 4
jobs:
  build:
    runs-on: Ubuntu-20.04  
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        df -h
    - name: login docker
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
        docker buildx create --use --name mybuilder
        docker buildx inspect mybuilder --bootstrap
        docker buildx ls
    - name: docker elecv2p
      run: |
        docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/elecv2p --platform=linux/arm64,linux/amd64,linux/arm/v7 . --push
